sudo: false
language: python
services:
- memcached
- mysql
- redis-server
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.cache
env:
  global:
    secure: RPClDmwFZnpBIKtMvlzjzZVam4flvJtSvxFD8mHCQVQ//KqyBbQxl970kqStOK7p0RXkOB3XuFDvVixqyuptoQ8wTdgSBEPAub4DwRpcmCc1exzErHIt9zep3cQhSUuzl8N/tNl3o6GG04NsZTeErORqxfDvk3WbqFa9593G358=
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - portaudio19-dev
    - python3.5
    - python3.5-dev
install:
- pip install --upgrade pip wheel virtualenv
- pip install --upgrade nox-automation coverage
- pip install --upgrade git+https://github.com/dhermes/ci-diff-helper.git
script:
- ./scripts/travis.sh
